[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing - return index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper MIME types for SPA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
